OPERA_20_SKILLS = {
    "doc_write": {"name": "문서 작성·편집", "desc": "한글/워드/텍스트 문서 작성 및 편집", "cat": "office"},
    "excel_data": {"name": "엑셀 데이터 가공", "desc": "openpyxl로 엑셀 데이터 분석/가공", "cat": "office"},
    "email_send": {"name": "이메일 작성·발송", "desc": "SMTP 이메일 작성 및 발송", "cat": "communication"},
    "web_search": {"name": "웹 검색·정보 수집", "desc": "웹 검색 및 페이지 데이터 수집", "cat": "research"},
    "report_gen": {"name": "보고서 생성", "desc": "데이터 수집 → 요약 → 문서화", "cat": "office"},
    "translate": {"name": "번역", "desc": "다국어 번역 (한/영/중/일)", "cat": "utility"},
    "pdf_summary": {"name": "PDF 읽고 요약", "desc": "PDF 텍스트 추출 → AI 요약", "cat": "research"},
    "ocr": {"name": "OCR (이미지→텍스트)", "desc": "이미지/화면 캡처 → 텍스트 변환", "cat": "utility"},
    "file_search": {"name": "파일 검색·내용 분석", "desc": "내부 문서 내용 기반 검색", "cat": "utility"},
    "stock_info": {"name": "주식/시세/뉴스 수집", "desc": "실시간 주가, 시세, 뉴스 수집", "cat": "research"},
    "code_gen": {"name": "코딩·스크립트 자동 생성", "desc": "Python/JS 코드 생성 및 실행", "cat": "dev"},
    "data_analysis": {"name": "데이터 분석·통계", "desc": "CSV/JSON 분석, 차트 생성", "cat": "office"},
    "schedule_mgmt": {"name": "일정·할일 관리", "desc": "캘린더 일정 등록 및 관리", "cat": "utility"},
    "messenger": {"name": "메신저 발송", "desc": "TG/Slack/카톡 메시지 발송", "cat": "communication"},
    "clipboard": {"name": "클립보드 관리", "desc": "클립보드 읽기/쓰기/히스토리", "cat": "utility"},
    "sys_info": {"name": "시스템 정보 조회", "desc": "CPU/메모리/디스크/프로세스 현황", "cat": "utility"},
    "auto_script": {"name": "반복 작업 자동화", "desc": "매크로 녹화/재생/스크립트 생성", "cat": "automation"},
    "grammar": {"name": "문법·맞춤법 검사", "desc": "한국어/영어 문법 및 맞춤법 검사", "cat": "utility"},
    "web_monitor": {"name": "웹사이트 변경 감지", "desc": "정기 fetch + 변경 내용 비교", "cat": "automation"},
    "db_query": {"name": "DB 쿼리·데이터 추출", "desc": "SQL 생성 및 실행, 데이터 추출", "cat": "dev"},
}
